ALTER TABLE users
DROP CONSTRAINT fk_users_role_id;

ALTER TABLE users
MODIFY COLUMN role_id BIGINT NOT NULL;

ALTER TABLE users
ADD CONSTRAINT fk_users_role_id FOREIGN KEY (role_id) REFERENCES roles (id)
    ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE users
MODIFY COLUMN role_id BIGINT NOT NULL;